import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Yoodle",
  description: "Terms and conditions for using the Yoodle platform.",
};

export default function TermsOfServicePage() {
  return (
    <article className="prose-legal">
      <h1
        className="text-3xl font-black text-[var(--text-primary)] mb-2"
        style={{ fontFamily: "var(--font-heading)" }}
      >
        Terms of Service
      </h1>
      <p className="text-sm text-[var(--text-secondary)] mb-8" style={{ fontFamily: "var(--font-body)" }}>
        Last updated: March 9, 2026
      </p>

      <div className="space-y-8 text-[var(--text-primary)]" style={{ fontFamily: "var(--font-body)" }}>
        <section>
          <h2 className="text-lg font-bold text-[var(--text-primary)] mb-3" style={{ fontFamily: "var(--font-heading)" }}>
            1. Acceptance of Terms
          </h2>
          <p className="leading-relaxed">
            By accessing or using Yoodle (&quot;the Service&quot;), you agree to be bound by these
            Terms of Service. If you do not agree to these terms, you may not use the Service. If
            you are using the Service on behalf of an organization, you represent that you have
            authority to bind that organization.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--text-primary)] mb-3" style={{ fontFamily: "var(--font-heading)" }}>
            2. Description of Service
          </h2>
          <p className="leading-relaxed">
            Yoodle is a video meeting and collaboration platform that provides video calls, AI-powered
            meeting notes, workspace management, task boards, calendar integration,
            and ephemeral ghost rooms. The Service is provided &quot;as is&quot; and may be updated,
            modified, or discontinued at our discretion.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--text-primary)] mb-3" style={{ fontFamily: "var(--font-heading)" }}>
            3. Account Registration
          </h2>
          <ul className="list-disc pl-6 space-y-1 leading-relaxed">
            <li>You must provide accurate and complete registration information</li>
            <li>You are responsible for maintaining the security of your account</li>
            <li>You must notify us immediately of any unauthorized access</li>
            <li>One person may not maintain more than one account</li>
            <li>You must be at least 16 years of age to use the Service</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--text-primary)] mb-3" style={{ fontFamily: "var(--font-heading)" }}>
            4. Acceptable Use
          </h2>
          <p className="leading-relaxed mb-2">You agree not to:</p>
          <ul className="list-disc pl-6 space-y-1 leading-relaxed">
            <li>Use the Service for any illegal purpose or in violation of any laws</li>
            <li>Record meetings without the knowledge and consent of all participants</li>
            <li>Share meeting recordings or transcripts without participant consent</li>
            <li>Attempt to bypass security measures, rate limits, or access controls</li>
            <li>Transmit malware, spam, or other harmful content</li>
            <li>Impersonate others or misrepresent your affiliation</li>
            <li>Use automated systems (bots, scrapers) to access the Service without permission</li>
            <li>Reverse-engineer, decompile, or attempt to extract source code (except as permitted by the MIT license for open-source components)</li>
            <li>Interfere with or disrupt the Service or servers connected to the Service</li>
            <li>Use the AI features to generate harmful, discriminatory, or misleading content</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--text-primary)] mb-3" style={{ fontFamily: "var(--font-heading)" }}>
            5. Content and Data
          </h2>
          <h3 className="text-base font-semibold text-[var(--text-primary)] mb-2">Your Content</h3>
          <p className="leading-relaxed mb-3">
            You retain ownership of all content you upload, create, or share through the Service
            (meeting recordings, messages, files). By using the Service, you grant Yoodle a limited
            license to store, process, and transmit your content as necessary to provide the Service.
          </p>

          <h3 className="text-base font-semibold text-[var(--text-primary)] mb-2">AI-Generated Content</h3>
          <p className="leading-relaxed mb-3">
            Meeting summaries, action items, and insights generated by our AI features are provided
            for convenience. We do not guarantee their accuracy or completeness. You are responsible
            for reviewing and verifying AI-generated content before relying on it.
          </p>

          <h3 className="text-base font-semibold text-[var(--text-primary)] mb-2">Ghost Rooms</h3>
          <p className="leading-relaxed">
            Content in ghost rooms is ephemeral and automatically deleted after 4 hours. We do not
            provide recovery of expired ghost room content. Users are advised not to share sensitive
            information that needs to be retained.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--text-primary)] mb-3" style={{ fontFamily: "var(--font-heading)" }}>
            6. Third-Party Services
          </h2>
          <p className="leading-relaxed">
            Yoodle integrates with third-party services including Google Workspace, AI providers
            (Google Gemini), and infrastructure providers. Your use of
            these integrations is subject to the respective third-party terms and privacy policies.
            Yoodle is not responsible for the availability, accuracy, or practices of third-party
            services.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--text-primary)] mb-3" style={{ fontFamily: "var(--font-heading)" }}>
            7. Billing and Payments
          </h2>
          <p className="leading-relaxed">
            Certain features of Yoodle may require a paid subscription. Payment terms, pricing, and
            plan details are presented at the time of purchase. Subscriptions renew automatically
            unless cancelled before the renewal date. Refunds are handled on a case-by-case basis.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--text-primary)] mb-3" style={{ fontFamily: "var(--font-heading)" }}>
            8. Intellectual Property
          </h2>
          <p className="leading-relaxed">
            Yoodle&apos;s source code is available under the MIT License. The Yoodle name, logo,
            branding, and design are proprietary. You may not use our trademarks without prior
            written consent.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--text-primary)] mb-3" style={{ fontFamily: "var(--font-heading)" }}>
            9. Limitation of Liability
          </h2>
          <p className="leading-relaxed">
            To the maximum extent permitted by law, Yoodle and its affiliates shall not be liable for
            any indirect, incidental, special, consequential, or punitive damages, including loss of
            data, revenue, or business opportunities, arising from your use of the Service. Our total
            liability for any claim shall not exceed the amount you paid us in the 12 months preceding
            the claim.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--text-primary)] mb-3" style={{ fontFamily: "var(--font-heading)" }}>
            10. Disclaimer of Warranties
          </h2>
          <p className="leading-relaxed">
            The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties
            of any kind, whether express or implied, including but not limited to implied warranties of
            merchantability, fitness for a particular purpose, and non-infringement. We do not
            guarantee uninterrupted or error-free service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--text-primary)] mb-3" style={{ fontFamily: "var(--font-heading)" }}>
            11. Termination
          </h2>
          <p className="leading-relaxed">
            We may suspend or terminate your account at any time for violation of these terms, with or
            without notice. Upon termination, your right to use the Service ceases immediately. You
            may delete your account at any time through the Settings page. Data deletion follows the
            schedule described in our Privacy Policy.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--text-primary)] mb-3" style={{ fontFamily: "var(--font-heading)" }}>
            12. Changes to Terms
          </h2>
          <p className="leading-relaxed">
            We reserve the right to modify these Terms at any time. We will provide notice of
            significant changes via email or in-app notification. Continued use of the Service after
            changes constitutes acceptance of the revised terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--text-primary)] mb-3" style={{ fontFamily: "var(--font-heading)" }}>
            13. Governing Law
          </h2>
          <p className="leading-relaxed">
            These Terms shall be governed by and construed in accordance with the laws of the
            State of Colorado, United States, without regard to conflict of law principles.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--text-primary)] mb-3" style={{ fontFamily: "var(--font-heading)" }}>
            14. Contact
          </h2>
          <p className="leading-relaxed">
            For questions about these Terms, contact us at <strong>legal@yoodle.app</strong>.
          </p>
        </section>
      </div>
    </article>
  );
}
